[package]
name = "internet_identity_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bytes = "0.11"
candid = "0.8"
serde = "1"
ic-cdk = "0.6"
