[package]
name = "canister_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
flate2 = "1.0"
hex = "0.4.3"
lazy_static = "1.4"
regex = "1.5"
serde = "1"
serde_cbor = "0.11"
serde_bytes = "0.11"
sha2 = "0.10"

internet_identity_interface = { path = "../internet_identity_interface" }
state_machine_client = { path = "../state_machine_client" }

# All IC deps
candid = "0.8"
ic-cdk = "0.6"
ic-types = { git = "https://github.com/dfinity/ic", rev = "cec9976e224701d89082796dfcfb63727c80e167" }
ic-sdk-certification = { package="ic-certification", version="0.23" }
ic-sdk-types = { package="ic-types", version="0.6" }
ic-certification = { git = "https://github.com/dfinity/ic", rev = "cec9976e224701d89082796dfcfb63727c80e167" }
ic-crypto-iccsa = { git = "https://github.com/dfinity/ic", rev = "cec9976e224701d89082796dfcfb63727c80e167" }
ic-crypto-utils-threshold-sig-der = { git = "https://github.com/dfinity/ic", rev = "cec9976e224701d89082796dfcfb63727c80e167" }
