[package]
name = "canister_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
flate2 = "1.0"
hex = "0.4.3"
lazy_static = "1.4"
regex = "1.5"
serde = "1"
serde_cbor = "0.11"
serde_bytes = "0.11"
sha2 = "0.10"

internet_identity_interface = { path = "../internet_identity_interface" }

# All IC deps
candid = "0.8"
ic-cdk = "0.6"
ic-types = { git = "https://github.com/dfinity/ic", rev = "5248f11c18ca564881bbb82a4eb6915efb7ca62f" }
ic-sdk-types = { package="ic-types", version="0.6" }
ic-certification = { git = "https://github.com/dfinity/ic", rev = "5248f11c18ca564881bbb82a4eb6915efb7ca62f" }
ic-crypto-iccsa = { git = "https://github.com/dfinity/ic", rev = "5248f11c18ca564881bbb82a4eb6915efb7ca62f" }
ic-state-machine-tests = { git = "https://github.com/dfinity/ic", rev = "5248f11c18ca564881bbb82a4eb6915efb7ca62f" }
