# The "official" docker build. This is a pretty long build (~20mn) which we
# only run on master.
name: Docker build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t internet-identity .
      - run: mkdir out/
      - run: docker run --rm --entrypoint cat internet-identity /internet_identity.wasm > out/internet_identity.wasm
      - run: docker run --rm --entrypoint tar internet-identity -c -f - dist| tar -C out -x
      - run: sha256sum out/internet_identity.wasm
      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: Backend wasm module
          path: out/internet_identity.wasm
      - name: 'Upload more artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: Frontend assets
          path: out/dist
